os:
  - linux
language: rust
rust:
  - 1.28.0
  - 1.34.0
script:
  - echo TRV "$TRAVIS_RUST_VERSION"
  - cargo build --no-default-features --verbose --all
  - test "$TRAVIS_RUST_VERSION" = 1.28.0 || cargo test --no-default-features --verbose --all
  - cargo build --all-features --verbose --all
  - test "$TRAVIS_RUST_VERSION" = 1.28.0 || cargo test --all-features --verbose --all
