os:
  - linux
language: rust
rust:
  - 1.28.0
script:
  - cargo build --no-default-features --verbose --all
  - cargo test --no-default-features --verbose --all
  - cargo build --all-features --verbose --all
  - cargo test --all-features --verbose --all
